version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6

    commands:
      - bundle install
  build:
    commands:
      - JEKYLL_ENV=production bundle exec jekyll build

artifacts:
  base-directory: '_site'
  files:
    - '**/*'
